# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "This lane prepares application deployment to AppStore"
  lane :prepare_for_production do

    # checkout release branch
#    ensure_git_status_clean

    # clear cached data
#    clear_derived_data
#    xcclean(scheme: "geekShop", workspace: "geekShop.xcworkspace")

    # update pods
#    cocoapods(use_bundle_exec: false)

    # run tests
#    run_tests

    # take screenshots
#    capture_ios_screenshots
  end

  desc "This lane builds the project"
  lane :prepare_project do
    # Automatically increase application's build number
    increment_build_number

    # Build project
    gym(
      scheme: "geekShop",
      configuration: "Debug",
      export_method: "development",
      include_symbols: true,
      include_bitcode: true,
      silent: false
    )
  end
end
