# A list of devices you want to take the screenshots from
  devices([
    "iPhone 8 Plus",
    "iPad Pro (12.9-inch)"
  ])

  languages([
    "ru-RU",
    "en-US"
  ])

# The name of the scheme which contains the UI Tests
  scheme("snapshotGeekShopUITests")

# Where should the resulting screenshots be stored?
  output_directory("./screenshots")

# Clear all previously generated screenshots before creating new ones
  clear_previous_screenshots(true)
